const bodyCarouselData = [
    {
        image: "https://images.unsplash.com/photo-1664575600796-ffa828c5cb6e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        title: "Example Case Study ttttttttttttttttttttttttttttttttttttttttttttttttttt",
        description: "1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias corporis nemo necessitatibus nostrum laboriosam ipsa et amet sint dolore vero. Consequatur quidem ea nulla cum iste beatae, corrupti recusandae distinctio cupiditate inventore voluptatum vitae, sed quo eligendi eos natus. Accusamus, eligendi inventore sint impedit voluptatem provident aperiam dolor ad minus incidunt itaque, laboriosam minima, non libero! Nam expedita dolorum voluptate beatae tempora debitis aliquid aut possimus dolorem sapiente nobis nihil molestias commodi voluptatem corporis, dolor consequatur optio! Quam consequuntur recusandae molestiae alias rem sequi ex natus praesentium, veniam ipsa modi voluptatum adipisci unde hic! Dignissimos repudiandae, eius qui aperiam sunt aut magnam vero similique voluptas! Adipisci cupiditate ullam deserunt. Modi nesciunt cumque sit illo quisquam velit quas ipsa, tenetur aperiam unde sunt minima, cupiditate enim debitis architecto rem dolor iure maiores quos, facere impedit. Modi harum nesciunt magni aperiam nihil sed ipsam pariatur inventore nobis assumenda impedit, magnam, facilis unde. Natus quibusdam voluptatum officiis. Qui, inventore necessitatibus rerum natus porro quae quis? Minima praesentium est rem quibusdam sunt blanditiis deserunt soluta dolore id error tenetur sed, adipisci autem voluptate odit minus at enim hic dolores. Reprehenderit nam adipisci nemo cum ipsa at reiciendis velit? Illum delectus itaque nobis laborum vitae.",
        url: "example-case-study"
    },
    {
        image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        title: "CRM System for bank",
        description: "2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias corporis nemo necessitatibus nostrum laboriosam ipsa et amet sint dolore vero. Consequatur quidem ea nulla cum iste beatae, corrupti recusandae distinctio cupiditate inventore voluptatum vitae, sed quo eligendi eos natus. Accusamus, eligendi inventore sint impedit voluptatem provident aperiam dolor ad minus incidunt itaque, laboriosam minima, non libero! Nam expedita dolorum voluptate beatae tempora debitis aliquid aut possimus dolorem sapiente nobis nihil molestias commodi voluptatem corporis, dolor consequatur optio! Quam consequuntur recusandae molestiae alias rem sequi ex natus praesentium, veniam ipsa modi voluptatum adipisci unde hic! Dignissimos repudiandae, eius qui aperiam sunt aut magnam vero similique voluptas! Adipisci cupiditate ullam deserunt. Modi nesciunt cumque sit illo quisquam velit quas ipsa, tenetur aperiam unde sunt minima, cupiditate enim debitis architecto rem dolor iure maiores quos, facere impedit. Modi harum nesciunt magni aperiam nihil sed ipsam pariatur inventore nobis assumenda impedit, magnam, facilis unde. Natus quibusdam voluptatum officiis. Qui, inventore necessitatibus rerum natus porro quae quis? Minima praesentium est rem quibusdam sunt blanditiis deserunt soluta dolore id error tenetur sed, adipisci autem voluptate odit minus at enim hic dolores. Reprehenderit nam adipisci nemo cum ipsa at reiciendis velit? Illum delectus itaque nobis laborum vitae.",
        url: "crm-bank"
    },
    {
        image: "https://images.unsplash.com/photo-1504711331083-9c895941bf81?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        title: "Third example",
        description: "3 Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias corporis nemo necessitatibus nostrum laboriosam ipsa et amet sint dolore vero. Consequatur quidem ea nulla cum iste beatae, corrupti recusandae distinctio cupiditate inventore voluptatum vitae, sed quo eligendi eos natus. Accusamus, eligendi inventore sint impedit voluptatem provident aperiam dolor ad minus incidunt itaque, laboriosam minima, non libero! Nam expedita dolorum voluptate beatae tempora debitis aliquid aut possimus dolorem sapiente nobis nihil molestias commodi voluptatem corporis, dolor consequatur optio! Quam consequuntur recusandae molestiae alias rem sequi ex natus praesentium, veniam ipsa modi voluptatum adipisci unde hic! Dignissimos repudiandae, eius qui aperiam sunt aut magnam vero similique voluptas! Adipisci cupiditate ullam deserunt. Modi nesciunt cumque sit illo quisquam velit quas ipsa, tenetur aperiam unde sunt minima, cupiditate enim debitis architecto rem dolor iure maiores quos, facere impedit. Modi harum nesciunt magni aperiam nihil sed ipsam pariatur inventore nobis assumenda impedit, magnam, facilis unde. Natus quibusdam voluptatum officiis. Qui, inventore necessitatibus rerum natus porro quae quis? Minima praesentium est rem quibusdam sunt blanditiis deserunt soluta dolore id error tenetur sed, adipisci autem voluptate odit minus at enim hic dolores. Reprehenderit nam adipisci nemo cum ipsa at reiciendis velit? Illum delectus itaque nobis laborum vitae.",
        url: "third-example"
    },
    {
        image: "https://images.unsplash.com/photo-1577774438656-768f1e5d9ed6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        title: "Another entry to the carousel",
        description: "4 Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias corporis nemo necessitatibus nostrum laboriosam ipsa et amet sint dolore vero. Consequatur quidem ea nulla cum iste beatae, corrupti recusandae distinctio cupiditate inventore voluptatum vitae, sed quo eligendi eos natus. Accusamus, eligendi inventore sint impedit voluptatem provident aperiam dolor ad minus incidunt itaque, laboriosam minima, non libero! Nam expedita dolorum voluptate beatae tempora debitis aliquid aut possimus dolorem sapiente nobis nihil molestias commodi voluptatem corporis, dolor consequatur optio! Quam consequuntur recusandae molestiae alias rem sequi ex natus praesentium, veniam ipsa modi voluptatum adipisci unde hic! Dignissimos repudiandae, eius qui aperiam sunt aut magnam vero similique voluptas! Adipisci cupiditate ullam deserunt. Modi nesciunt cumque sit illo quisquam velit quas ipsa, tenetur aperiam unde sunt minima, cupiditate enim debitis architecto rem dolor iure maiores quos, facere impedit. Modi harum nesciunt magni aperiam nihil sed ipsam pariatur inventore nobis assumenda impedit, magnam, facilis unde. Natus quibusdam voluptatum officiis. Qui, inventore necessitatibus rerum natus porro quae quis? Minima praesentium est rem quibusdam sunt blanditiis deserunt soluta dolore id error tenetur sed, adipisci autem voluptate odit minus at enim hic dolores. Reprehenderit nam adipisci nemo cum ipsa at reiciendis velit? Illum delectus itaque nobis laborum vitae.",
        url: "another-entry"
    }
]

export default bodyCarouselData;